CREATE TABLE IF NOT EXISTS room_images(
image_id SERIAL PRIMARY KEY,
room_id INTEGER NOT NULL,
alt TEXT NOT NULL,
title TEXT NOT NULL,
path TEXT NOT NULL,
public_id TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_room_id
FOREIGN KEY (room_id) REFERENCES rooms(room_id) ON DELETE CASCADE
)