spring.application.name=api-gateway
spring.profiles.active=local
jwt.secret=77sn3A/2oqGqR5xZQNGj/B9zzqJa8d4wcDSw20xk4VE=
jwt.access-token.expiration=3600000

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param