server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/room_service_app
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
  pattern:
    level: "%5p [requestId=%X{requestId}, traceId=%X{traceId}, spanId=%X{spanId}]"

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
