spring.application.name=price-service
###############################################
# DATASOURCE – Hauptverbindung
###############################################

spring.datasource.url=jdbc:postgresql://localhost:5432/price_service_app
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


###############################################
# FLYWAY – nutzt die Spring-Datasource,
# aber initialisiert NICHT die Schemas
###############################################

spring.flyway.enabled=true

# WICHTIG: Flyway soll NICHT versuchen, die DB zu bauen,
# sondern nur Migrationen ausführen.
spring.flyway.create-schemas=false

# Flyway nutzt die Spring-Datasource → Credentials stimmen.
# KEINE eigene URL, KEIN eigener User, KEIN eigenes Passwort.


###############################################
# JPA / HIBERNATE – startet nach Hikari
###############################################

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.multipart=DEBUG
logging.level.com.fasterxml.jackson=DEBUG

###############################################
# DEVTOOLS – deaktiviert
###############################################

spring.devtools.restart.enabled=false


###############################################
# Rest unverändert
###############################################

spring.profiles.active=local
jwt.secret=77sn3A/2oqGqR5xZQNGj/B9zzqJa8d4wcDSw20xk4VE=
jwt.access-token.expiration=3600000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB
server.tomcat.max-http-post-size=50MB

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param


