apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      - name: room-service
        image: romanarmin/sliced-backend-room-service:latest
        ports:
          - containerPort: 8083
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
